# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_level.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_level(object):
    def setupUi(self, level):
        level.setObjectName("level")
        level.resize(238, 260)
        self.label = QtWidgets.QLabel(level)
        self.label.setGeometry(QtCore.QRect(40, 50, 161, 20))
        self.label.setObjectName("label")
        self.easy = QtWidgets.QRadioButton(level)
        self.easy.setGeometry(QtCore.QRect(80, 80, 82, 18))
        self.easy.setObjectName("easy")
        self.medium = QtWidgets.QRadioButton(level)
        self.medium.setGeometry(QtCore.QRect(80, 120, 82, 18))
        self.medium.setObjectName("medium")
        self.hard = QtWidgets.QRadioButton(level)
        self.hard.setGeometry(QtCore.QRect(80, 160, 82, 18))
        self.hard.setObjectName("hard")
        self.ok = QtWidgets.QPushButton(level)
        self.ok.setGeometry(QtCore.QRect(180, 210, 31, 31))
        self.ok.setObjectName("ok")

        self.retranslateUi(level)
        QtCore.QMetaObject.connectSlotsByName(level)

    def retranslateUi(self, level):
        _translate = QtCore.QCoreApplication.translate
        level.setWindowTitle(_translate("level", "Сложность"))
        self.label.setText(_translate("level", "Выберите уровень сложности"))
        self.easy.setText(_translate("level", "Легкий"))
        self.medium.setText(_translate("level", "Средний"))
        self.hard.setText(_translate("level", "Сложный"))
        self.ok.setText(_translate("level", "OK"))
