# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'promote_pawn.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Promote_form(object):
    def setupUi(self, Promote_form):
        Promote_form.setObjectName("Promote_form")
        Promote_form.resize(501, 183)
        self.promote_to_rook = QtWidgets.QPushButton(Promote_form)
        self.promote_to_rook.setGeometry(QtCore.QRect(0, 50, 111, 111))
        self.promote_to_rook.setText("")
        self.promote_to_rook.setIconSize(QtCore.QSize(64, 64))
        self.promote_to_rook.setObjectName("promote_to_rook")
        self.promote_to_knight = QtWidgets.QPushButton(Promote_form)
        self.promote_to_knight.setGeometry(QtCore.QRect(260, 50, 111, 111))
        self.promote_to_knight.setText("")
        self.promote_to_knight.setIconSize(QtCore.QSize(64, 64))
        self.promote_to_knight.setObjectName("promote_to_knight")
        self.promote_to_bishop = QtWidgets.QPushButton(Promote_form)
        self.promote_to_bishop.setGeometry(QtCore.QRect(130, 50, 111, 111))
        self.promote_to_bishop.setText("")
        self.promote_to_bishop.setIconSize(QtCore.QSize(64, 64))
        self.promote_to_bishop.setObjectName("promote_to_bishop")
        self.promote_to_queen = QtWidgets.QPushButton(Promote_form)
        self.promote_to_queen.setGeometry(QtCore.QRect(390, 50, 111, 111))
        self.promote_to_queen.setText("")
        self.promote_to_queen.setIconSize(QtCore.QSize(64, 64))
        self.promote_to_queen.setObjectName("promote_to_queen")
        self.promote = QtWidgets.QLabel(Promote_form)
        self.promote.setGeometry(QtCore.QRect(200, 10, 99, 23))
        self.promote.setObjectName("promote")

        self.retranslateUi(Promote_form)
        QtCore.QMetaObject.connectSlotsByName(Promote_form)

    def retranslateUi(self, Promote_form):
        _translate = QtCore.QCoreApplication.translate
        Promote_form.setWindowTitle(_translate("Promote_form", "Promote"))
        self.promote.setText(_translate("Promote_form", " Превратить пешку"))
